FROM ubuntu:18.04

RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m pip install --upgrade pip

WORKDIR /app
COPY . .

RUN python3 -m pip install -r requirements.txt

ARG SCRIPT

CMD python3 ${SCRIPT}.py